### ISSUE TITLE
Reading non-ASCII symbol

### ISSUE THREAD

**Issue by franckevicz** [galkahana/pdf-text-extraction#22]
Hello!
I am trying to read quite complicated PDF with various symbols and I receive a lot of broken symbols.
Originally I found this issue while reading the German language, and all umlauts (ä, ö, ü) were badly interpreted in the resulting file.

`.\TextExtraction.exe "C:\Users\misha\cloudplan\documentos\UTF-8 test file.pdf" >> utf_test.txt`

[UTF-8 test file.pdf](https://github.com/galkahana/pdf-text-extraction/files/13206921/UTF-8.test.file.pdf)
[utf_test.txt](https://github.com/galkahana/pdf-text-extraction/files/13206931/utf_test.txt)

**UPD:**
problem was in windows pipes :) using it with the flag -o fixed issue

**Comment by galkahana** [comment]
thanks for your note. One thing. I believe the key difference between -o option and the symbols that you saw have to do with a missing utf8 bom.

you see. the CLI emits the output as a utf8 encoded text. if you pipe this as is into a file with no bom at its header then later when opening the file in a text editor, the result is platform dependent. on windows the default encoding is utf16. I think the problems you saw are because of this contradiction. on Mac the default encoding is utf8 which is why if you tried the same thing there it'd work well.

when using the -o option the code emits a utf8 bom at the beginning of the file which then means that the operating system, whatever it is, will read the text correctly.
